server:
  port: 8080

spring:
  application:
    name: news-server
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: ${MONGO_DATABASE}

article:
  limit: 20
  today: 5
  db: ${ARTICLE_DATABASE}

logging:
  level:
    reactor.netty: DEBUG
