spring:
  application:
    name: kidsnews-server
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: ${MONGO_DATABASE}
article:
  limit: 20
  today: 5
  table: ${TABLE_NAME}