spring:
  application:
    name: record-server
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: ${MONGO_DATABASE}

article:
  limit: 20
  today: 5
  db: ${ARTICLE_DATABASE}
