server:
  port: 8082

spring:
  application:
    name: mypage-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: ${MONGO_DATABASE}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

article:
  limit: 20
  today: 5
  db: ${ARTICLE_DATABASE}
