server:
  port: 8082

spring:
  application:
    name: mypage-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://218.49.207.146:31765/newkiz
    username: root
    password: Rkskek123!
  data:
    mongodb:
      uri: mongodb://admin:Rkskek123!@218.49.207.146:31240/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: newkiz

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

article:
  limit: 20
  today: 5
  db: articles_test
