spring:
  cloud:
    gateway:
      routes:
        - id: news-service
          uri: http://news-service.${K8S_NAMESPACE}.svc.cluster.local
          predicates:
            - Path=/api/news/**
#          filters:
#            - RewritePath=/api/news/(?<segment>.*), /$\{segment}

        - id: mypage-service
          uri: http://mypage-service.${K8S_NAMESPACE}.svc.cluster.local
          predicates:
            - Path=/api/mypage/**

        - id: records-service
          uri: http://records-service.${K8S_NAMESPACE}.svc.cluster.local
          predicates:
            - Path=/api/records/**

        - id: shorts-service
          uri: http://shorts-service.${K8S_NAMESPACE}.svc.cluster.local
          predicates:
            - Path=/api/shorts/**

        - id: kidsnews-service
          uri: http://kidsnews-service.${K8S_NAMESPACE}.svc.cluster.local
          predicates:
            - Path=/api/kidsnews/**

        - id: game-service
          uri: http://game-service.${K8S_NAMESPACE}.svc.cluster.local
          predicates:
            - Path=/api/game/**

  r2dbc:
    url: r2dbc:pool:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}


